# Generated by Django 4.1.3 on 2022-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('price', models.FloatField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='static/myapp')),
                ('status', models.CharField(choices=[('SELLING', 'Selling'), ('RENTING', 'Renting')], max_length=100)),
                ('date_posted', models.DateField(auto_now=True)),
            ],
        ),
    ]
