# Generated by Django 4.1.3 on 2022-11-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_alter_listing_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
